service: authoriaztion-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-1
  environment:

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
    events:
      - http:
          path: auth
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin
